// Code generated by MockGen. DO NOT EDIT.
// Source: repository.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	models "github.com/thinhlu123/shortener/internal/models"
)

// MockLinkRepository is a mock of LinkRepository interface.
type MockLinkRepository struct {
	ctrl     *gomock.Controller
	recorder *MockLinkRepositoryMockRecorder
}

// MockLinkRepositoryMockRecorder is the mock recorder for MockLinkRepository.
type MockLinkRepositoryMockRecorder struct {
	mock *MockLinkRepository
}

// NewMockLinkRepository creates a new mock instance.
func NewMockLinkRepository(ctrl *gomock.Controller) *MockLinkRepository {
	mock := &MockLinkRepository{ctrl: ctrl}
	mock.recorder = &MockLinkRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLinkRepository) EXPECT() *MockLinkRepositoryMockRecorder {
	return m.recorder
}

// CreateShortLink mocks base method.
func (m *MockLinkRepository) CreateShortLink(arg0 context.Context, arg1 models.Link) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateShortLink", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateShortLink indicates an expected call of CreateShortLink.
func (mr *MockLinkRepositoryMockRecorder) CreateShortLink(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateShortLink", reflect.TypeOf((*MockLinkRepository)(nil).CreateShortLink), arg0, arg1)
}

// GetLink mocks base method.
func (m *MockLinkRepository) GetLink(arg0 context.Context, arg1 models.Link) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLink", arg0, arg1)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLink indicates an expected call of GetLink.
func (mr *MockLinkRepositoryMockRecorder) GetLink(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLink", reflect.TypeOf((*MockLinkRepository)(nil).GetLink), arg0, arg1)
}

// GetListLink mocks base method.
func (m *MockLinkRepository) GetListLink(arg0 context.Context, arg1 models.Link) ([]models.Link, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetListLink", arg0, arg1)
	ret0, _ := ret[0].([]models.Link)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetListLink indicates an expected call of GetListLink.
func (mr *MockLinkRepositoryMockRecorder) GetListLink(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetListLink", reflect.TypeOf((*MockLinkRepository)(nil).GetListLink), arg0, arg1)
}

// IncreaseClickCount mocks base method.
func (m *MockLinkRepository) IncreaseClickCount(arg0 context.Context, arg1 models.Link) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IncreaseClickCount", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// IncreaseClickCount indicates an expected call of IncreaseClickCount.
func (mr *MockLinkRepositoryMockRecorder) IncreaseClickCount(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncreaseClickCount", reflect.TypeOf((*MockLinkRepository)(nil).IncreaseClickCount), arg0, arg1)
}
