global:
  scrape_interval:     10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'system'
    static_configs:
      - targets: ['node_exporter:9100']

#  - job_name: 'mongo-healthcheck'
#    static_configs:
#      - targets: ['mongo_service:27017']
#
#  - job_name: 'redis-healthcheck'
#    static_configs:
#      - targets: ['redis:6379']
#
#  - job_name: 'shortener-healthcheck'
#    static_configs:
#      - targets: ['shortener:5555']